from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from pathlib import Path
from reportlab.lib.styles import getSampleStyleSheet

from pathlib import Path
styles = getSampleStyleSheet()


class ReportGenerator:

    def generate(
        self,
        patient,
        results,
        recommendations,
        filename="Health_Report.pdf"
    ):
        REPORTS_DIR = Path("reports")

        REPORTS_DIR.mkdir(exist_ok=True)

        filename = REPORTS_DIR / filename
        filename = str(filename)
        pdf = SimpleDocTemplate(str(filename))
        elements = []

        elements.append(

            Paragraph(
                "<b>AI Preventive Healthcare Report</b>",
                styles["Title"]
            )

        )

        elements.append(Spacer(1,20))

        elements.append(

            Paragraph(

                f"<b>Patient:</b> {patient['full_name']}",

                styles["Normal"]

            )

        )

        elements.append(

            Paragraph(

                f"<b>Age:</b> {patient['age']}",

                styles["Normal"]

            )

        )

        elements.append(

            Paragraph(

                f"<b>BMI:</b> {patient['bmi']:.2f}",

                styles["Normal"]

            )

        )

        elements.append(Spacer(1,20))
        elements.append(

            Paragraph(

                f"<b>Overall Health Score:</b> {recommendations['health_score']}/100",

                styles["Normal"]

            )

        )

        elements.append(

            Paragraph(

                f"<b>Overall Risk:</b> {recommendations['overall_risk']}",

                styles["Normal"]

            )

        )

        elements.append(Spacer(1,20))
        elements.append(

                Paragraph(

                        "<b>Disease Risks</b>",

                        styles["Heading2"]

                )

        )

        elements.append(

            Paragraph(

                f"Diabetes : {results['diabetes_probability']*100:.1f}%",

                styles["Normal"]

            )

        )

        elements.append(

            Paragraph(

                f"Hypertension : {results['hypertension_probability']*100:.1f}%",

                styles["Normal"]

            )

        )

        elements.append(

            Paragraph(

                f"Hyperlipidemia : {results['hyperlipidemia_probability']*100:.1f}%",

                styles["Normal"]

            )

        )

        elements.append(Spacer(1,20))

        elements.append(

            Paragraph(

                "<b>Recommendations</b>",

                styles["Heading2"]

            )

        )

        for rec in recommendations["recommendations"]:

            elements.append(

                Paragraph(

                    f"• {rec}",

                    styles["Normal"]

                )

            )

        elements.append(Spacer(1,20))

        elements.append(

            Paragraph(

                "<b>Suggested Tests</b>",

                styles["Heading2"]

            )

        )

        for test in recommendations["tests"]:

            elements.append(

                Paragraph(

                    f"• {test}",

                    styles["Normal"]

                )

            )
        elements.append(Spacer(1,20))

        elements.append(

            Paragraph(

                "<b>Disclaimer</b>",

                styles["Heading2"]

            )

        )

        elements.append(

            Paragraph(

                "This report is generated by an AI screening system. It is intended for early risk assessment only and should not replace professional medical diagnosis or consultation.",

                styles["Normal"]

            )

        )

        pdf.build(elements)

        return filename


report_generator = ReportGenerator()
##